title: "Sustainable Waste Resource Recovery Lab"
description: "UT Austin | Fariborz Maseeh Department of Civil, Architectural and Environmental Engineering"

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

# Load only our custom CSS
stylesheet: custom

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
